### PR TITLE
Tell users about messages they missed

### PR DESCRIPTION
**Pull request by gabebw**
Just write "hey future joe, that client called" and Hubot will give them the 
message when they enter the room again. It searches for messages containing " 
future ".

### CODE REVIEW

**Comment by gabebw** [comment]
Fixes #5.

**Comment by drapergeek** [comment]
@gabebw I haven't looked through this but the functionality seems very similar to this: https://github.com/github/hubot-scripts/blob/master/src/scripts/tell.coffee 

Just giving a point of reference.

**Comment by gabebw** [comment]
Yeah, I based some of my code on that, actually. Theirs doesn't persist to the DB though.

**Comment by drapergeek** [comment]
:cool: Just wanted to make sure you were aware. Love the idea!

**Comment by mcmire** [comment]
Sick! I like.

**Comment by gabebw** [comment]
I'll merge this. Let's see how it goes!

**Pull request merged**
