### PR TITLE
Remove 'future' command

### PR DESCRIPTION
**Pull request by gfontenot**
This thing doesn't work, and is only annoying. Lets turn it off.

### CODE REVIEW

**Comment by gabebw** [comment]
:+1:

**Comment by calebhearth** [comment]
Yes please. (It does work, but the detection is pretty wonky).

**Comment by gabebw** [comment]
If people signed out of Campfire, it'd work!

**Comment by calebhearth** [comment]
Sure, but "In the future it'll work" shouldn't be triggering the command.

**Comment by calebhearth** [comment]
Another option would be to check
1. `/^future (\w+)/i`
2. That `$1` isn't the name of a person currently signed in

**Comment by jferris** [comment]
Instead of waiting until somebody signed in, it might be more effective to wait until somebody says something.

**Comment by gfontenot** [comment]
Merged this in. I don't know where the script itself lives, but improvement discussion could probably be moved there.

**Comment by gabebw** [comment]
The problem is that it detects when people "sign back in"...but nobody signs out! So they never "come back". I think the whole concept is flawed.

**Pull request merged**
